---
name: kreversi
version: 17.08.1
summary: Reversi Board Game
description: KReversi is a simple one player strategy game played against the computer.
    If a player's piece is captured by an opposing player, that piece is turned over
    to reveal the color of that player. A winner is declared when one player has more
    pieces of his own color on the board and there are no more possible moves.
confinement: strict
grade: stable
apps:
    kreversi:
        command: kf5-launch kreversi
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kreversi
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kreversi:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - libkf5kdegames-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kreversi-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
